export default class ANSIPhysicalLayout {
  rows = [
    [
      'Backquote',
      'Digit1',
      'Digit2',
      'Digit3',
      'Digit4',
      'Digit5',
      'Digit6',
      'Digit7',
      'Digit8',
      'Digit9',
      'Digit0',
      'Minus',
      'Equal',
      'Backspace',
    ],
    [
      'Tab',
      'KeyQ',
      'KeyW',
      'KeyE',
      'KeyR',
      'KeyT',
      'KeyY',
      'KeyU',
      'KeyI',
      'KeyO',
      'KeyP',
      'BracketLeft',
      'BracketRight',
      'Backslash',
    ],
    [
      'CapsLock',
      'KeyA',
      'KeyS',
      'KeyD',
      'KeyF',
      'KeyG',
      'KeyH',
      'KeyJ',
      'KeyK',
      'KeyL',
      'Semicolon',
      'Quote',
      'Enter',
    ],
    [
      'ShiftLeft',
      'KeyZ',
      'KeyX',
      'KeyC',
      'KeyV',
      'KeyB',
      'KeyN',
      'KeyM',
      'Comma',
      'Period',
      'Slash',
      'ShiftRight',
    ],
    [
      'ControlLeft',
      'MetaLeft',
      'AltLeft',
      'Space',
      'AltRight',
      'MetaRight',
      'ContextMenu',
      'ControlRight',
    ],
  ];

  defaultCharCodesMap = {
    32: 'Space',
    39: 'Quote',
    44: 'Comma',
    45: 'Minus',
    46: 'Period',
    47: 'Slash',
    48: 'Digit0',
    49: 'Digit1',
    50: 'Digit2',
    51: 'Digit3',
    52: 'Digit4',
    53: 'Digit5',
    54: 'Digit6',
    55: 'Digit7',
    56: 'Digit8',
    57: 'Digit9',
    59: 'Semicolon',
    61: 'Equal',
    91: 'BracketLeft',
    92: 'Backslash',
    93: 'BracketRight',
    96: 'Backquote',
    97: 'KeyA',
    98: 'KeyB',
    99: 'KeyC',
    100: 'KeyD',
    101: 'KeyE',
    102: 'KeyF',
    103: 'KeyG',
    104: 'KeyH',
    105: 'KeyI',
    106: 'KeyJ',
    107: 'KeyK',
    108: 'KeyL',
    109: 'KeyM',
    110: 'KeyN',
    111: 'KeyO',
    112: 'KeyP',
    113: 'KeyQ',
    114: 'KeyR',
    115: 'KeyS',
    116: 'KeyT',
    117: 'KeyU',
    118: 'KeyV',
    119: 'KeyW',
    120: 'KeyX',
    121: 'KeyY',
    122: 'KeyZ',
    33: 'ShiftRight Digit1',
    34: 'ShiftLeft Quote',
    35: 'ShiftRight Digit3',
    36: 'ShiftRight Digit4',
    37: 'ShiftRight Digit5',
    38: 'ShiftLeft Digit7',
    40: 'ShiftLeft Digit9',
    41: 'ShiftLeft Digit0',
    42: 'ShiftLeft Digit8',
    43: 'ShiftLeft Equal',
    58: 'ShiftLeft Semicolon',
    60: 'ShiftLeft Comma',
    62: 'ShiftLeft Period',
    63: 'ShiftLeft Slash',
    64: 'ShiftRight Digit2',
    65: 'ShiftRight KeyA',
    66: 'ShiftRight KeyB',
    67: 'ShiftRight KeyC',
    68: 'ShiftRight KeyD',
    69: 'ShiftRight KeyE',
    70: 'ShiftRight KeyF',
    71: 'ShiftRight KeyG',
    72: 'ShiftLeft KeyH',
    73: 'ShiftLeft KeyI',
    74: 'ShiftLeft KeyJ',
    75: 'ShiftLeft KeyK',
    76: 'ShiftLeft KeyL',
    77: 'ShiftLeft KeyM',
    78: 'ShiftLeft KeyN',
    79: 'ShiftLeft KeyO',
    80: 'ShiftLeft KeyP',
    81: 'ShiftRight KeyQ',
    82: 'ShiftRight KeyR',
    83: 'ShiftRight KeyS',
    84: 'ShiftRight KeyT',
    85: 'ShiftLeft KeyU',
    86: 'ShiftRight KeyV',
    87: 'ShiftRight KeyW',
    88: 'ShiftRight KeyX',
    89: 'ShiftLeft KeyY',
    90: 'ShiftRight KeyZ',
    94: 'ShiftLeft Digit6',
    95: 'ShiftLeft Minus',
    123: 'ShiftLeft BracketLeft',
    124: 'ShiftLeft Backslash',
    125: 'ShiftLeft BracketRight',
    126: 'ShiftRight Backquote',
  };
}
